### ISSUE TITLE
Langserve Tutorial - RuntimeError: no validator found for <class 'rag_conversation.chain.ChatHistory'>, see `arbitrary_types_allowed` in Config

### ISSUE THREAD

**Issue by dalssoft** [langchain-ai/langserve#270]
I'm trying to run the [langserve tutorial](https://www.youtube.com/watch?v=o7C9ld6Ln-M) and after fix errors related to rust (tiktoken, apparently) and API keys, now I'm getting the following error:

```
RuntimeError: no validator found for <class 'rag_conversation.chain.ChatHistory'>, see `arbitrary_types_allowed` in Config
``` 

Can someone help me?

Context: I'm a experienced nodejs developer who is trying to learn LangChain and, by extension, Python. So it may be a newbie error.

Steps:

```shell
langchain app new my_new_app --package rag-conversation
```

When asked for `rag-conversation` download, I answered `y`.

To run the project, I'm using the following command:

```shell
langchain serve
```

The only change I made to the code was to add the following line to the `server.py` file:

```python
from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from langserve import add_routes

app = FastAPI()

@app.get("/")
async def redirect_root_to_docs():
    return RedirectResponse("/docs")
# --->
from rag_conversation import chain as rag_conversation_chain

add_routes(app, rag_conversation_chain, path="/rag-conversation")
# <---

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
```

extra infos:
Using pyenv, python 3.12.0
MacOS Ventura 13.4, M2
VSCode

**Comment by eyurtsev** [comment]
Hello @dalssoft !

You're likely using pydantic >=2 which doesn't work well with langchain right now (if you're curious read langchain guidelines on how to work with pydantic 2)

If that's the case, could you downgrade to pydantic 1.10.13? 

```
pip install pydantic==1.10.13
```

hopefully this works for you!

Let me know if there's still an issue afterwards.

The template should be importing langchain.pydantic_v1 instead of pydantic so we should fix that in the template -- if you're curious you can read the discussions of handling pydantic with langchain
