### ISSUE TITLE
Feature Request: Serve LangChain as an OpenAI API Compatible Server

### ISSUE THREAD

**Issue by 2catycm** [langchain-ai/langserve#396]
In many LLM Application, OpenAI API is a widely used format. These applications directly use ChatGPT via api key and openai client library. After that, they are empowered by LLM and have there functions. 
It is a common need to change the LLM (e.g. change to LangChain/RAG enabled LLM; or just change to another LLM), but it is not easy to change the code in these applications.
We can run a server locally that is OpenAI API compatible, and change the OPENAI_BASE_URL env variable that the LLM application would use. 

Can LangServe do that?

**Comment by 2catycm** [comment]
For input and output are both a single str type, this is possible.

**Comment by eyurtsev** [comment]
LangChain provides a compatibility layer over all chat models regardless of provider since all chat models follow more or less the same API. 

Here's a server that allows serving both Anthropic and OpenAI models: https://github.com/langchain-ai/langserve/blob/main/examples/llm/server.py

Use Configurable Runnables to allow run time configuration of the chat model; e.g., that could be used with OpenAI chat models to control parameters like temperature or model name based on information provided on the client side.

You can use configurable runnables to select between chat models with entirely different underlying APIs; e.g., Anthropic and control which model is used using run time parameters as well.

Hope this helps.

**Comment by eyurtsev** [comment]
The RemoteRunnable client takes care of serialization of well known LangChain primitives like AIMessage / HumanMessage / FunctionMessage etc (so it works with non string types out of the box)

**Comment by 2catycm** [comment]
> LangChain provides a compatibility layer over all chat models regardless of provider since all chat models follow more or less the same API.
> 
> Here's a server that allows serving both Anthropic and OpenAI models: https://github.com/langchain-ai/langserve/blob/main/examples/llm/server.py
> 
> Use Configurable Runnables to allow run time configuration of the chat model; e.g., that could be used with OpenAI chat models to control parameters like temperature or model name based on information provided on the client side.
> 
> You can use configurable runnables to select between chat models with entirely different underlying APIs; e.g., Anthropic and control which model is used using run time parameters as well.
> 
> Hope this helps.

That is great. LangChain and LangServe based software can use the same batch/stream/async API while having different configuration via Configurable Runnable with a variety of LLMs.

But I am considering programs that are not LangChain based. These programs may use openai with the openai python lib directly. I am considering to make a proxy server that is compatible with OpenAI, but it actually invokes LangChain developped Agents.

**Comment by 2catycm** [comment]
> The RemoteRunnable client takes care of serialization of well known LangChain primitives like AIMessage / HumanMessage / FunctionMessage etc (so it works with non string types out of the box)

That's cool

**Comment by eyurtsev** [comment]
> But I am considering programs that are not LangChain based. These programs may use openai with the openai python lib directly. I am considering to make a proxy server that is compatible with OpenAI, but it actually invokes LangChain developped Agents.

Could you elaborate? 

It sounds like the client code is not langchain based, but the server code is langchain based (since it's running a langchain agent?)  Is that the scenario you're thinking about?

**Comment by 2catycm** [comment]
> > But I am considering programs that are not LangChain based. These programs may use openai with the openai python lib directly. I am considering to make a proxy server that is compatible with OpenAI, but it actually invokes LangChain developped Agents.
> 
> Could you elaborate?
> 
> It sounds like the client code is not langchain based, but the server code is langchain based (since it's running a langchain agent?) Is that the scenario you're thinking about?

Yes, LangChain Agent as a Model as a Service. which is what langserve is doing. 
langserve's API has its format as indicated in langserve documentation. 

Application based on LLM are too assorted to enumerate. They are of various kind. Not all of them have leveraged LangChain, while they all must at least support ChatGPT API, which is of https://platform.openai.com/docs/api-reference/chat/create?lang=python format

**Comment by eyurtsev** [comment]
Got it -- LangServe won't be helpful for this use case since it's optimized for serving LangChain runnables

Creating an Open AI like API sounds pretty straight forward using vanilla LangChain and Fast API. LangChain provides a uniform interface over a lot of LLMs, so you would need to write an adapter between Open AI like interface and the LangChain runnable interface. (This is not a feature we're likely to develop since we haven't seen many users request it and I suspect that there are already 3rd party providers that do exactly that.)

**Comment by 2catycm** [comment]
> Got it -- LangServe won't be helpful for this use case since it's optimized for serving LangChain runnables
> 
> Creating an Open AI like API sounds pretty straight forward using vanilla LangChain and Fast API. LangChain provides a uniform interface over a lot of LLMs, so you would need to write an adapter between Open AI like interface and the LangChain runnable interface. (This is not a feature we're likely to develop since we haven't seen many users request it and I suspect that there are already 3rd party providers that do exactly that.)

got it, thanks for your detailed reply

**Comment by PlebeiusGaragicus** [comment]
Came here wondering the same.

I think a good example use case is a project like Open WebUI.  It can easily serve Ollama models as well as connect to OpenAI compatible APIs.

**But**, there's no easy way to incorporate LangServe.  LangServe gives the typical /stream, /batch, /astream_events, etc endpoints.... but these aren't OpenAI compatible and thus I need to find work-arounds and add layers in order to get this to work.

**Comment by Schumacher-Bastian** [comment]
Yes, this would be a great feature.

**Comment by reteps** [comment]
I found this: https://github.com/samuelint/langchain-openai-api-bridge which seems to fit my usecase.

**Comment by 2catycm** [comment]
> I found this: https://github.com/samuelint/langchain-openai-api-bridge which seems to fit my usecase.

Looks great!
