### ISSUE TITLE
Add healthcheck endpoint to langserve

### ISSUE THREAD

**Issue by Swalloow** [langchain-ai/langserve#427]
The healthcheck endpoint is needed in the langserve project provisioning.
If deploying to a K8S environment, users will need it for the liveness probe.

**Comment by eyurtsev** [comment]
Hi @Swalloow,

LangServe is designed to extend an existing Fast API app. Developers are free to define and add any other endpoints that are needed including both liveness and readiness probes. 

While LangServe could add a liveness probe automatically, it shouldn't since it doesn't add much value and could conflict with an existing liveness probe. LangServe cannot automatically add a readiness probe since that depends on the rest of the application state which is only known to the application developer.
