### ISSUE TITLE
langchain serve using different folder

### ISSUE THREAD

**Issue by SoulEvill** [langchain-ai/langserve#727]
I have different folder structure that I cannot have server.py under app folder. so when I use langchain serve - it will throw error: "ERROR:    Error loading ASGI app. Could not import module "app.server".

It doesnt seem the langchain serve accept path parameters - is there any workaround to make it work? Any suggestion would be really appreciated thanks!

**Comment by eyurtsev** [comment]
The path parameter is for specifying the path to the endpoint on the server not where the code lives. 

You need to set up your python environment properly (e.g., by installing the packages that you're developing or else updating the PYTHON_PATH to see all the relevant packages). You should be able to get chat-gpt to help with this as it's a python environment configuration question rather than anything that's langserve or langchain specific.
